### PR TITLE
Actualize Erlang versions list and add Cowboy section to README

### PR DESCRIPTION
**Pull request by lexmag**
@goshakkk WDYT

### CODE REVIEW

**Comment by lexmag** [comment]
friendly ping

**Comment by goshacmd** [comment]
Oh, sorry for not acting on this before. Looks good to me. Can you please reopen so that I can merge? Cheers.

**Comment by lexmag** [comment]
I've already deleted branch, so I can't reopen it. But you can apply it as patches:
- https://github.com/goshakkk/heroku-buildpack-elixir/commit/6ce7fa8dc96096f852ea75d53fda418b632c9ced.patch
- https://github.com/goshakkk/heroku-buildpack-elixir/commit/848cc49d8b2a7d8ed6cc4a74eeee641438524f5c.patch

And please ignore the last commit (1d3a80ec33a505d39c5cd1b8e2692d4e28ab79ae).

**Comment by goshacmd** [comment]
Applied. Thank you!

**Pull request closed without merging**
